### ISSUE TITLE
Deleting a partition created by mkfat.py causes error: The request is not supported

### ISSUE THREAD

**Issue by DMW007** [maxpat78/FATtools#3]
Hello,

I'm trying to create a FAT32 partition on my SD card. It's attached as removeable media with the ID 2 in `diskpart`:

```
DISKPART> list disk

  Datenträger ###  Status         Größe    Frei     Dyn  GPT
  ---------------  -------------  -------  -------  ---  ---
  Datenträger 0    Online          100 GB  1024 KB
  Datenträger 1    Kein Medium        0 B      0 B
  Datenträger 2    Online           29 GB      0 B

DISKPART> select disk 2
DISKPART> clean
```
Now `list partition` shows me a message that there are no partitions on the disk, so it should be wiped. To create the partition, I call the `mkfat.py` script in an administrator cmd shell (I have cloned the entire repo in my working directory):

```cmd
python mkfat.py \\.\PHYSICALDRIVE2 --fstype fat32
```
This take some time and then shows the following output:

```
Successfully applied FAT32 to a 29.81 GiB volume.
1952836 clusters of 16.0 KB.
29.80 GiB free in 1952835 clusters.

FAT #1 @0x4000, Data Region @0xEEA400, Root (cluster #2) @0xEEA400
```
The Windows Explorer shows a empty 32GB FAT32 partition and it seems to work, I could copy files on it. During my tests, I'd like to re-format it again, so my test case was to copy some files on the newly formatted card, run `mkfat.py` again and I'd expect to have an empty partition again.

But the second call throws an _access denied_ error:
```
Traceback (most recent call last):
  File "c:\Users\Daniel\Downloads\FATtools-master\mkfat.py", line 102, in <module>
    format(dsk, dsk.size, params=params)
  File "c:\Users\Daniel\Downloads\FATtools-master\FATtools\mkfat.py", line 484, in fat32_mkfs
    stream.write(bytearray(boot.cluster))
  File "c:\Users\Daniel\Downloads\FATtools-master\FATtools\disk.py", line 338, in write
    self._file.write(s[:full_blocks*512])
  File "c:\Users\Daniel\Downloads\FATtools-master\FATtools\disk.py", line 113, in write
    raise BaseException('WriteFile failed with code %d (%s)' % (GetLastError(), FormatError()))
BaseException: WriteFile failed with code 5 (Zugriff verweigert)
```
I guessed that I may need to remove the existing partition first. The disk management shows an error _this request is not supported_:

![grafik](https://user-images.githubusercontent.com/21245043/147854647-2a6ae17e-68a6-419c-bb39-5d502565f9cf.png)

Using diskpart, neither the disk with the id 2, nor the volume (G:) is shown any more

```
DISKPART> list disk

  Datenträger ###  Status         Größe    Frei     Dyn  GPT
  ---------------  -------------  -------  -------  ---  ---
  Datenträger 0    Online          100 GB  1024 KB
  Datenträger 1    Kein Medium        0 B      0 B
  Datenträger 3    Kein Medium        0 B      0 B
  Datenträger 4    Kein Medium        0 B      0 B

DISKPART> list volume

  Volume ###  Bst  Bezeichnung  DS     Typ         Größe    Status     Info
  ----------  ---  -----------  -----  ----------  -------  ---------  --------
  Volume 0     D   VBox_GAs_6.  CDFS   CD            58 MB  Fehlerfre
  Volume 1         System-rese  NTFS   Partition     50 MB  Fehlerfre  System
  Volume 2     C                NTFS   Partition     99 GB  Fehlerfre  Startpar
  Volume 3                      NTFS   Partition    524 MB  Fehlerfre  Versteck
  Volume 4     E                       Wechselmed      0 B  Kein Medi
  Volume 6     H                       Wechselmed      0 B  Kein Medi
  Volume 7     I                       Wechselmed      0 B  Kein Medi
```
I had to close the shell window and start diskpart in a new one

```
DISKPART> list disk

  Datenträger ###  Status         Größe    Frei     Dyn  GPT
  ---------------  -------------  -------  -------  ---  ---
  Datenträger 0    Online          100 GB  1024 KB
  Datenträger 1    Kein Medium        0 B      0 B
  Datenträger 2    Online           29 GB      0 B
  Datenträger 3    Kein Medium        0 B      0 B
  Datenträger 4    Kein Medium        0 B      0 B

DISKPART> list volume

  Volume ###  Bst  Bezeichnung  DS     Typ         Größe    Status     Info
  ----------  ---  -----------  -----  ----------  -------  ---------  --------
  Volume 0     D   VBox_GAs_6.  CDFS   CD            58 MB  Fehlerfre
  Volume 1         System-rese  NTFS   Partition     50 MB  Fehlerfre  System
  Volume 2     C                NTFS   Partition     99 GB  Fehlerfre  Startpar
  Volume 3                      NTFS   Partition    524 MB  Fehlerfre  Versteck
  Volume 4     E                       Wechselmed      0 B  Kein Medi
  Volume 5     G                FAT32  Wechselmed    29 GB  Fehlerfre
```
I tried to delete the partition using diskpart, but I cannot select it. 

```
DISKPART> select disk 2
DISKPART> list partition

  Partition ###  Typ               Größe    Offset
  -------------  ----------------  -------  -------
* Partition 1    Primär              29 GB      0 B
```
When I try `select partition 1`, I get _There was no partition selected_. Because of the asterix and articles [like this](https://www.icare-recovery.com/howto/diskpart-delete-partition.html), I also called `select partition *`. It throws an error that the argument is invalid. `delete partition` also doesn't work and says there was no partition selected.

I try to disconnect and re-connect the USB card reader, restarted the entire VM and also tried it on a Windows 10 host without virtualization. When restarting the VM, Windows did a disk check on the card. But none of them worked. By playing around with the `readonly` attribute in diskpart
```
attributes disk clear readonly
```
it seems to get fixed one time. I tried to reproduce it for this ticket, doesn't work any more. 

The event view of Windows shows multiple warning that the devices (2,3 and 4) have assigned a ID like one or more devices who are connected with the system. It seems that all of them are from the cardreader, which has multiple slots and creates a device for each of them. The entry refers to [KB2983588](https://docs.microsoft.com/en-us/troubleshoot/windows-client/backup-and-storage/event-id-158-for-identical-disk-guids), which refers to install MPIO on Windows Server. However, this is a Desktop (Windows 10 21H1 Build 19043) so `Dism /online /enable-feature:MultipathIo` throws an error that this feature is unknown. I don't know if this warning is problematic. 

Do you have any idea why FATtools cause this problems? It seems caused by using this lib, I have flashed multiple images to the card with the same card reader. And I also created 2 times a FAT32 partition with the graphical Windows tools, it worked without any issues.

### Edit
I tried it with another card reader. A simple Micro-SD to USB converter. I don't get the warnings about device ids in the logs. But it's still not possible to delete the existing partition. The same error occurs when marking the partition as active. However, all other operations in the computer management GUI seems to work: Changing/deleting the drive letter as well as formatting the partition. Deleting is still not possible. Even after formatting the card with another file system like exFAT or NTFS.

### Edit 2: Strange workaround
It was possible to delete the partition with a strange workaround: Formatting it using the GUI without the checkbox for fast formatting, which is checked by default. Then right click on the running formatting in the computer management console and abort it. After that, the partition had changed to type RAW. I could delete it and re-create a FAT32 partition. Deleting seems now possible.

![grafik](https://user-images.githubusercontent.com/21245043/147856624-e735cef5-8a5f-4288-a78d-8008b59526ee.png)
 
Now I've deleted all partitions (using the second card reader now) and re-run `mkfat.py` with the same parameters. Just changed PHYSICALDRIVE2 to PHYSICALDRIVE1 since this has changed with the other card reader. The partition gets created, however I'm still unable to delete the partition like before :cry: 

### Edit: Partially working code
I tried to make a custom Python script to break down the problem:

```python
from FATtools import utils, partutils
from FATtools.Volume import vopen
from FATtools.mkfat import *

# Depending on the used cardreader, we have different device ids:
# 1 -> Simple USB-to-Micro-SD-Adapterm  2 -> UGREEN card reader with multiple slots
#dev = "\\\\.\\PHYSICALDRIVE1"
dev = "\\\\.\\PHYSICALDRIVE2"

disk = vopen(dev, 'r+b', 'disk')
print("Disk opened")

gpt = partutils.partition(disk)
# Throws KeyError: '\\\\.\\PHYSICALDRIVE2'
#disk.close()
print("Created partition")

# Also tried partition1 since "list partition" in diskpart shows the first partition as partition 1
# Throws the same error and gave me a 2048 GB GPT protection partition...
# Could not be removed in the computer management UI, but by re-running the script with partition0
part = vopen(dev, 'r+b', 'partition0')
print("Opened partition for formatting")

# Throws BaseException: WriteFile failed with code 5 (permission denied)
exfat_mkfs(part, (gpt.partitions[0].u64EndingLBA-gpt.partitions[0].u64StartingLBA+1)*512)
print("Formatting done")
```
This seems to work, I can delete the partition without any error. But I wondered that my partition is formatted, even when the `exfat_mkfs` call throws an access denied error? I thought that my partition would be created but not formatted after this error.

It seems that something is wrong here. I copied some data on the card, deleted the partition in the UI and re-run the script again. Instead of an empty FAT32 card, it contains all the data _before_ deleting the partition!

#### _KeyError_ on `disk.close()`
It took out that `win32_disk.open_handles` in `disk.py` is empty, since [`partutils.partition` already closes the disk](https://github.com/maxpat78/FATtools/blob/master/FATtools/partutils.py#L283). So it seems for me that this call in [`mkfat.py`](https://github.com/maxpat78/FATtools/blob/26bb88db15270fd80c1ddd8d3774f013a9d6a645/mkfat.py#L49) is wrong. I just need to re-call `vopen` to getch the first partition, which should exists after `partutils.partition` was called successfully. But the formatting still doesn't work and throws _code 5 access denied_. The program runs as Administrator, so I can't understand this.

**Comment by maxpat78** [comment]
Are you able to succesfully use DISKPART to create and delete partitions on *ALL* your USB sticks and SD cards (and, particularly, on such test SD card) in Windows 10?

I've just tried myself with an old 2GB SD card, and encountered similar/other errors/problems (in fact, I used a disk editor to blank some very first sectors in the SD, so obtaining a RAW disk Windows can happily manage).

Such behavior could depend also on Windows itself, that did/does NOT like people to partition removable media like USB sticks and SD cards AND puts many security restrictions around direct disk access (however, command to properly partition and format is mkfat.py -p MBR|GPT, or it will create/format a volume).
In fact, it seems that Windows wants to see a partition in hard disks, virtual VHD(X) disks and SOME sticks/SDs, while other sticks/SDs have to present a simple file system (=volume) on them.
Some times is mandatory to phisically disconnect media from system to reset them and commit partition changes, also.

**Comment by maxpat78** [comment]
I've replaced the close member in disk.py with:
```
    def close(self):
        if self.name in win32_disk.open_handles:
            windll.kernel32.CloseHandle(self.handle)
            self.closed = True
            del win32_disk.open_handles[self.name]
```
and found that mkfat.py stops with EINVMBR while re-opening the new partition that is supposed to have been just created on 
 my 2GB SD card under Windows 10: in fact WriteFile calls return no errors, but data are not really written to disk, I suspect.

Please note that accessing a VHD via ``\\.\PhysicalDrive2`` works correctly - you can partition and format many times and then delete the partition with DISKPART.

**Comment by maxpat78** [comment]
On a cleaned 2GB Windows 10 SD Card, I issued the following command
```
    py -m mkfat -p MBR -t fat32 \\.\physicaldrive1
```    
three times. The results were:
(1) OK
(2) BaseException: WriteFile failed with code 5 (Accesso negato.) while disk.write((2<<20)*b'\x00')
    BUT PRESSING F5 IN DISKPART CHANGES FROM FAT32 TO RAW.
    A disk editor shows that only the first MB has been written!
    It stops just before the mounted volume!
(3) OK, it performs again both partitioning and formatting.

Note: partition gets regularly deleted in DISKPART with
```    
sel dis 1
sel par 1
del par
```    

The problem I guess here is explicitly dismounting all mounted volumes on ``\\.\PhysicalDrive1`` BEFORE getting an handle to it.

**Comment by maxpat78** [comment]
Please try the new code (with volume dismounting support).

I did many experiments with the old code and DISKPART, and found that repeatedly re-partitioning with partition scheme swap could lead to unacessible SD card/VHD (I've restored the SD booting Linux Debian, at last).
The same using mkfat.py to partition a card containing multiple GPT partitions created with DISKPART (phantom zero-sized drives were reported inserting the card in a USB reader).

I suppose the real cause of the malfunctioning could reside in Windows disk changer (it locks some disk extents? it looks at older GPT structures laying around?).
