### ISSUE TITLE
It doesn't write VDI dynamic virtual hard disk

### ISSUE THREAD

**Issue by FeelUsM** [maxpat78/FATtools#4]
I create new virtual machine in VirtualBox with VDI dynamic virtual hard disk.
I mount image of this hard disk with [ImDisk](https://sourceforge.net/projects/imdisk-toolkit/) in my host windows 8.1 (without creating any file system).
I read this disk in python:
```
VOLUME_PATH = r'\\.\D:'
with open(VOLUME_PATH, 'r+b') as disk:
    disk.seek(0)
    data=disk.read(512)
data
```
and I get `b'<<< Oracle VM VirtualBox Disk Image >>>\n\x00\x00 ...`
Then I unmount this image from host windows.
Then I write my own code (like nodos/nodos in your repository) to image with your library:
```
from FATtools.Volume import *
disk = vopen('VirtualBox VMs\\ddos\\ddos.vdi', 'r+b', 'disk')
disk.seek(0)
disk.write(b"\xb8\x03\x00\xcd\x10\xb4\x0a\xb0\x71\xbb\x00\x00\xb9\x02\x00\xcd\x10\xeb\xfe")
disk.close()
```
Then I again mount ddos.vdi with ImDisk to host OS and read it
and I get nothing changes in this vdi, I get again  `b'<<< Oracle VM VirtualBox Disk Image >>>\n\x00\x00 ...`
(VirtualBox also print, that no bootable media, when I try to start it with this image)
Where is my wroted data?

**Comment by maxpat78** [comment]
As far as I know, ImDisk can mount any file as a RAW disk image and pass the raw sectors to the OS file systems parser: ImDisk by itself can't recognize the underlying virtual disk format (VDI, VHD, VMDK, etc.).

So, with your first code fragment you read nothing but the very first bytes of the VDI file (the Oracle disclaimer).

Your second code fragment opens, and writes to, the emulated virtual *disk* sector zero, not the plain VDI file: your data were written to the first VDI payload block, which comes after the VDI block allocation table (BAT) in the VDI file - probably around 2MB offset. Obviously, the VDI *file* beginning is left unchanged. 

Please note that only FIXED VDIs can get mounted with ImDisk and the -b offset trick: dynamic disks can have data blocks placed in arbitrary order!

**Comment by FeelUsM** [comment]
Yes you are right. I forgot to place MBR signature:
```python
head=b"\xb8\x03\x00\xcd\x10\xb4\x0a\xb0\x71\xbb\x00\x00\xb9\x02\x00\xcd\x10\xeb\xfe"
tail=b'\x55\xAA'
sector=head+b'\x00'*(512-len(head)-2)+b'\x55\xAA'
from FATtools.Volume import *
disk = vopen('ddos\\ddos.vdi', 'r+b', 'disk')
disk.seek(0)
disk.write(sector)
disk.close()
```

Also I start reading your code and found in [VDI image close method](https://github.com/maxpat78/FATtools/blob/master/FATtools/vdiutils.py#L264) that if some exception occurred in try block nobody knows about it (if debug mode is disabled)
