### ISSUE TITLE
A few questions, I deem important

### ISSUE THREAD

**Issue by RedstonedLife** [maxpat78/FATtools#9]
So, I like `FATtools`, It's a very useful package. But, I would like to see a proper documentation instead of some sample code
for example, a question I've been wondering around is, Is it possible to use a VHD .img file as an actual VHD. Instead of an img that just saves bytes. I.e like simulate a FS. I.e have a virtual `C:` drive that I can write to read to and use as a regular HDD.
Because the sample examples do not explain it well, nor do they show the possibility, I've heard from other sources that it is possible.
But either you have to use 3rd party packages that are not in python or you have to make your own until I stumbled upon FATtools
now to simplify this whole message the questions I have are the following

1. **Will there ever be a proper documentation as opposed to some examples?**
2. **Is it possible to simulate a HDD like in VMWare?**

**Comment by maxpat78** [comment]
1. I don't think so, at least if not written by someone else. It's a tool for "internal hacking purpose", not meant for general distribution.
2. No. Recent updates make it possible to "mix" disk access between Python and FATtools env, however.
